// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/federicoleon/go-httpclient/core"
	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type ClientMock
func (_mock *ClientMock) Delete(url string, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, headers)
	} else {
		tmpRet = _mock.Called(url)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...http.Header) error); ok {
		r1 = returnFunc(url, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClientMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Delete(url interface{}, headers ...interface{}) *ClientMock_Delete_Call {
	return &ClientMock_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *ClientMock_Delete_Call) Run(run func(url string, headers ...http.Header)) *ClientMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		var variadicArgs []http.Header
		if len(args) > 1 {
			variadicArgs = args[1].([]http.Header)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ClientMock_Delete_Call) Return(response *core.Response, err error) *ClientMock_Delete_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Delete_Call) RunAndReturn(run func(url string, headers ...http.Header) (*core.Response, error)) *ClientMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type ClientMock
func (_mock *ClientMock) Do(req *http.Request) (*core.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*core.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *core.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type ClientMock_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *ClientMock_Expecter) Do(req interface{}) *ClientMock_Do_Call {
	return &ClientMock_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *ClientMock_Do_Call) Run(run func(req *http.Request)) *ClientMock_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientMock_Do_Call) Return(response *core.Response, err error) *ClientMock_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Do_Call) RunAndReturn(run func(req *http.Request) (*core.Response, error)) *ClientMock_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ClientMock
func (_mock *ClientMock) Get(url string, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, headers)
	} else {
		tmpRet = _mock.Called(url)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...http.Header) error); ok {
		r1 = returnFunc(url, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClientMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Get(url interface{}, headers ...interface{}) *ClientMock_Get_Call {
	return &ClientMock_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{url}, headers...)...)}
}

func (_c *ClientMock_Get_Call) Run(run func(url string, headers ...http.Header)) *ClientMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		var variadicArgs []http.Header
		if len(args) > 1 {
			variadicArgs = args[1].([]http.Header)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ClientMock_Get_Call) Return(response *core.Response, err error) *ClientMock_Get_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Get_Call) RunAndReturn(run func(url string, headers ...http.Header) (*core.Response, error)) *ClientMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function for the type ClientMock
func (_mock *ClientMock) Options(url string, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, headers)
	} else {
		tmpRet = _mock.Called(url)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...http.Header) error); ok {
		r1 = returnFunc(url, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type ClientMock_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Options(url interface{}, headers ...interface{}) *ClientMock_Options_Call {
	return &ClientMock_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{url}, headers...)...)}
}

func (_c *ClientMock_Options_Call) Run(run func(url string, headers ...http.Header)) *ClientMock_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		var variadicArgs []http.Header
		if len(args) > 1 {
			variadicArgs = args[1].([]http.Header)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ClientMock_Options_Call) Return(response *core.Response, err error) *ClientMock_Options_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Options_Call) RunAndReturn(run func(url string, headers ...http.Header) (*core.Response, error)) *ClientMock_Options_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type ClientMock
func (_mock *ClientMock) Patch(url string, body interface{}, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, body, headers)
	} else {
		tmpRet = _mock.Called(url, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, body, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, ...http.Header) error); ok {
		r1 = returnFunc(url, body, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type ClientMock_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - body interface{}
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Patch(url interface{}, body interface{}, headers ...interface{}) *ClientMock_Patch_Call {
	return &ClientMock_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *ClientMock_Patch_Call) Run(run func(url string, body interface{}, headers ...http.Header)) *ClientMock_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []http.Header
		var variadicArgs []http.Header
		if len(args) > 2 {
			variadicArgs = args[2].([]http.Header)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ClientMock_Patch_Call) Return(response *core.Response, err error) *ClientMock_Patch_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Patch_Call) RunAndReturn(run func(url string, body interface{}, headers ...http.Header) (*core.Response, error)) *ClientMock_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type ClientMock
func (_mock *ClientMock) Post(url string, body interface{}, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, body, headers)
	} else {
		tmpRet = _mock.Called(url, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, body, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, ...http.Header) error); ok {
		r1 = returnFunc(url, body, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type ClientMock_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - body interface{}
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Post(url interface{}, body interface{}, headers ...interface{}) *ClientMock_Post_Call {
	return &ClientMock_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *ClientMock_Post_Call) Run(run func(url string, body interface{}, headers ...http.Header)) *ClientMock_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []http.Header
		var variadicArgs []http.Header
		if len(args) > 2 {
			variadicArgs = args[2].([]http.Header)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ClientMock_Post_Call) Return(response *core.Response, err error) *ClientMock_Post_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Post_Call) RunAndReturn(run func(url string, body interface{}, headers ...http.Header) (*core.Response, error)) *ClientMock_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostForm provides a mock function for the type ClientMock
func (_mock *ClientMock) PostForm(url string, body interface{}, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, body, headers)
	} else {
		tmpRet = _mock.Called(url, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PostForm")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, body, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, ...http.Header) error); ok {
		r1 = returnFunc(url, body, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_PostForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostForm'
type ClientMock_PostForm_Call struct {
	*mock.Call
}

// PostForm is a helper method to define mock.On call
//   - url string
//   - body interface{}
//   - headers ...http.Header
func (_e *ClientMock_Expecter) PostForm(url interface{}, body interface{}, headers ...interface{}) *ClientMock_PostForm_Call {
	return &ClientMock_PostForm_Call{Call: _e.mock.On("PostForm",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *ClientMock_PostForm_Call) Run(run func(url string, body interface{}, headers ...http.Header)) *ClientMock_PostForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []http.Header
		var variadicArgs []http.Header
		if len(args) > 2 {
			variadicArgs = args[2].([]http.Header)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ClientMock_PostForm_Call) Return(response *core.Response, err error) *ClientMock_PostForm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_PostForm_Call) RunAndReturn(run func(url string, body interface{}, headers ...http.Header) (*core.Response, error)) *ClientMock_PostForm_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type ClientMock
func (_mock *ClientMock) Put(url string, body interface{}, headers ...http.Header) (*core.Response, error) {
	var tmpRet mock.Arguments
	if len(headers) > 0 {
		tmpRet = _mock.Called(url, body, headers)
	} else {
		tmpRet = _mock.Called(url, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *core.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) (*core.Response, error)); ok {
		return returnFunc(url, body, headers...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...http.Header) *core.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, ...http.Header) error); ok {
		r1 = returnFunc(url, body, headers...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type ClientMock_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - body interface{}
//   - headers ...http.Header
func (_e *ClientMock_Expecter) Put(url interface{}, body interface{}, headers ...interface{}) *ClientMock_Put_Call {
	return &ClientMock_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *ClientMock_Put_Call) Run(run func(url string, body interface{}, headers ...http.Header)) *ClientMock_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []http.Header
		var variadicArgs []http.Header
		if len(args) > 2 {
			variadicArgs = args[2].([]http.Header)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ClientMock_Put_Call) Return(response *core.Response, err error) *ClientMock_Put_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ClientMock_Put_Call) RunAndReturn(run func(url string, body interface{}, headers ...http.Header) (*core.Response, error)) *ClientMock_Put_Call {
	_c.Call.Return(run)
	return _c
}
