// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"
	"time"

	"github.com/federicoleon/go-httpclient/gohttp"
	mock "github.com/stretchr/testify/mock"
)

// NewClientBuilderMock creates a new instance of ClientBuilderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientBuilderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientBuilderMock {
	mock := &ClientBuilderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientBuilderMock is an autogenerated mock type for the ClientBuilder type
type ClientBuilderMock struct {
	mock.Mock
}

type ClientBuilderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientBuilderMock) EXPECT() *ClientBuilderMock_Expecter {
	return &ClientBuilderMock_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) Build() gohttp.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 gohttp.Client
	if returnFunc, ok := ret.Get(0).(func() gohttp.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.Client)
		}
	}
	return r0
}

// ClientBuilderMock_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type ClientBuilderMock_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *ClientBuilderMock_Expecter) Build() *ClientBuilderMock_Build_Call {
	return &ClientBuilderMock_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *ClientBuilderMock_Build_Call) Run(run func()) *ClientBuilderMock_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientBuilderMock_Build_Call) Return(client gohttp.Client) *ClientBuilderMock_Build_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *ClientBuilderMock_Build_Call) RunAndReturn(run func() gohttp.Client) *ClientBuilderMock_Build_Call {
	_c.Call.Return(run)
	return _c
}

// DisableTimeouts provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) DisableTimeouts(disable bool) gohttp.ClientBuilder {
	ret := _mock.Called(disable)

	if len(ret) == 0 {
		panic("no return value specified for DisableTimeouts")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(bool) gohttp.ClientBuilder); ok {
		r0 = returnFunc(disable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_DisableTimeouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableTimeouts'
type ClientBuilderMock_DisableTimeouts_Call struct {
	*mock.Call
}

// DisableTimeouts is a helper method to define mock.On call
//   - disable bool
func (_e *ClientBuilderMock_Expecter) DisableTimeouts(disable interface{}) *ClientBuilderMock_DisableTimeouts_Call {
	return &ClientBuilderMock_DisableTimeouts_Call{Call: _e.mock.On("DisableTimeouts", disable)}
}

func (_c *ClientBuilderMock_DisableTimeouts_Call) Run(run func(disable bool)) *ClientBuilderMock_DisableTimeouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_DisableTimeouts_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_DisableTimeouts_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_DisableTimeouts_Call) RunAndReturn(run func(disable bool) gohttp.ClientBuilder) *ClientBuilderMock_DisableTimeouts_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnectionTimeout provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetConnectionTimeout(timeout time.Duration) gohttp.ClientBuilder {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for SetConnectionTimeout")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(time.Duration) gohttp.ClientBuilder); ok {
		r0 = returnFunc(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetConnectionTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnectionTimeout'
type ClientBuilderMock_SetConnectionTimeout_Call struct {
	*mock.Call
}

// SetConnectionTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *ClientBuilderMock_Expecter) SetConnectionTimeout(timeout interface{}) *ClientBuilderMock_SetConnectionTimeout_Call {
	return &ClientBuilderMock_SetConnectionTimeout_Call{Call: _e.mock.On("SetConnectionTimeout", timeout)}
}

func (_c *ClientBuilderMock_SetConnectionTimeout_Call) Run(run func(timeout time.Duration)) *ClientBuilderMock_SetConnectionTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetConnectionTimeout_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetConnectionTimeout_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetConnectionTimeout_Call) RunAndReturn(run func(timeout time.Duration) gohttp.ClientBuilder) *ClientBuilderMock_SetConnectionTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeaders provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetHeaders(headers http.Header) gohttp.ClientBuilder {
	ret := _mock.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for SetHeaders")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(http.Header) gohttp.ClientBuilder); ok {
		r0 = returnFunc(headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaders'
type ClientBuilderMock_SetHeaders_Call struct {
	*mock.Call
}

// SetHeaders is a helper method to define mock.On call
//   - headers http.Header
func (_e *ClientBuilderMock_Expecter) SetHeaders(headers interface{}) *ClientBuilderMock_SetHeaders_Call {
	return &ClientBuilderMock_SetHeaders_Call{Call: _e.mock.On("SetHeaders", headers)}
}

func (_c *ClientBuilderMock_SetHeaders_Call) Run(run func(headers http.Header)) *ClientBuilderMock_SetHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Header
		if args[0] != nil {
			arg0 = args[0].(http.Header)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetHeaders_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetHeaders_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetHeaders_Call) RunAndReturn(run func(headers http.Header) gohttp.ClientBuilder) *ClientBuilderMock_SetHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// SetHttpClient provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetHttpClient(c *http.Client) gohttp.ClientBuilder {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SetHttpClient")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(*http.Client) gohttp.ClientBuilder); ok {
		r0 = returnFunc(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetHttpClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHttpClient'
type ClientBuilderMock_SetHttpClient_Call struct {
	*mock.Call
}

// SetHttpClient is a helper method to define mock.On call
//   - c *http.Client
func (_e *ClientBuilderMock_Expecter) SetHttpClient(c interface{}) *ClientBuilderMock_SetHttpClient_Call {
	return &ClientBuilderMock_SetHttpClient_Call{Call: _e.mock.On("SetHttpClient", c)}
}

func (_c *ClientBuilderMock_SetHttpClient_Call) Run(run func(c *http.Client)) *ClientBuilderMock_SetHttpClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Client
		if args[0] != nil {
			arg0 = args[0].(*http.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetHttpClient_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetHttpClient_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetHttpClient_Call) RunAndReturn(run func(c *http.Client) gohttp.ClientBuilder) *ClientBuilderMock_SetHttpClient_Call {
	_c.Call.Return(run)
	return _c
}

// SetMaxIdleConnections provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetMaxIdleConnections(i int) gohttp.ClientBuilder {
	ret := _mock.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for SetMaxIdleConnections")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(int) gohttp.ClientBuilder); ok {
		r0 = returnFunc(i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetMaxIdleConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxIdleConnections'
type ClientBuilderMock_SetMaxIdleConnections_Call struct {
	*mock.Call
}

// SetMaxIdleConnections is a helper method to define mock.On call
//   - i int
func (_e *ClientBuilderMock_Expecter) SetMaxIdleConnections(i interface{}) *ClientBuilderMock_SetMaxIdleConnections_Call {
	return &ClientBuilderMock_SetMaxIdleConnections_Call{Call: _e.mock.On("SetMaxIdleConnections", i)}
}

func (_c *ClientBuilderMock_SetMaxIdleConnections_Call) Run(run func(i int)) *ClientBuilderMock_SetMaxIdleConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetMaxIdleConnections_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetMaxIdleConnections_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetMaxIdleConnections_Call) RunAndReturn(run func(i int) gohttp.ClientBuilder) *ClientBuilderMock_SetMaxIdleConnections_Call {
	_c.Call.Return(run)
	return _c
}

// SetResponseTimeout provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetResponseTimeout(timeout time.Duration) gohttp.ClientBuilder {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for SetResponseTimeout")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(time.Duration) gohttp.ClientBuilder); ok {
		r0 = returnFunc(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetResponseTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResponseTimeout'
type ClientBuilderMock_SetResponseTimeout_Call struct {
	*mock.Call
}

// SetResponseTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *ClientBuilderMock_Expecter) SetResponseTimeout(timeout interface{}) *ClientBuilderMock_SetResponseTimeout_Call {
	return &ClientBuilderMock_SetResponseTimeout_Call{Call: _e.mock.On("SetResponseTimeout", timeout)}
}

func (_c *ClientBuilderMock_SetResponseTimeout_Call) Run(run func(timeout time.Duration)) *ClientBuilderMock_SetResponseTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetResponseTimeout_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetResponseTimeout_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetResponseTimeout_Call) RunAndReturn(run func(timeout time.Duration) gohttp.ClientBuilder) *ClientBuilderMock_SetResponseTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserAgent provides a mock function for the type ClientBuilderMock
func (_mock *ClientBuilderMock) SetUserAgent(userAgent string) gohttp.ClientBuilder {
	ret := _mock.Called(userAgent)

	if len(ret) == 0 {
		panic("no return value specified for SetUserAgent")
	}

	var r0 gohttp.ClientBuilder
	if returnFunc, ok := ret.Get(0).(func(string) gohttp.ClientBuilder); ok {
		r0 = returnFunc(userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gohttp.ClientBuilder)
		}
	}
	return r0
}

// ClientBuilderMock_SetUserAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserAgent'
type ClientBuilderMock_SetUserAgent_Call struct {
	*mock.Call
}

// SetUserAgent is a helper method to define mock.On call
//   - userAgent string
func (_e *ClientBuilderMock_Expecter) SetUserAgent(userAgent interface{}) *ClientBuilderMock_SetUserAgent_Call {
	return &ClientBuilderMock_SetUserAgent_Call{Call: _e.mock.On("SetUserAgent", userAgent)}
}

func (_c *ClientBuilderMock_SetUserAgent_Call) Run(run func(userAgent string)) *ClientBuilderMock_SetUserAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientBuilderMock_SetUserAgent_Call) Return(clientBuilder gohttp.ClientBuilder) *ClientBuilderMock_SetUserAgent_Call {
	_c.Call.Return(clientBuilder)
	return _c
}

func (_c *ClientBuilderMock_SetUserAgent_Call) RunAndReturn(run func(userAgent string) gohttp.ClientBuilder) *ClientBuilderMock_SetUserAgent_Call {
	_c.Call.Return(run)
	return _c
}
